### ISSUE TITLE
No such variable: ch_expdesign

### ISSUE THREAD

**Issue by Ni-Ar** [nf-core/proteomicslfq#104]
Hi,

I'm running into an odd thing:

```
nextflow run main.nf -profile singularity --input ../data/raw/*.raw --database ../data/reference/proteome/Mouse_prot_database.fasta --outdir tmp  --allowed_missed_cleavages 3 -c crg.config 
```

Where `./data/raw/*.raw` is the relative path to my thermo raw files. I have 6 immunoprecipitation samples (n=3 control, n=3 KO), all label free, from the sample cells, and run on the same day. `-c crg.config`  is related to issue #103 .

The above command returns the following error:
```
N E X T F L O W  ~  version 20.07.1
Launching `main.nf` [nice_mercator] - revision: 18f2d39694
[-        ] process > raw_file_conversion          -
[-        ] process > mzml_indexing                -
[-        ] process > generate_decoy_database      -
[-        ] process > openms_peakpicker            -
[-        ] process > search_engine_msgf           -
[-        ] process > search_engine_comet          -
[-        ] process > index_peptides               -
[-        ] process > extract_percolator_features  -
[-        ] process > percolator                   -
[-        ] process > fdr_idpep                    -
[-        ] process > idpep                        -
[-        ] process > idscoreswitcher_to_qval      -
[-        ] process > consensusid                  -
[-        ] process > fdr_consensusid              -
[-        ] process > idfilter                     -
[-        ] process > idscoreswitcher_for_luciphor -
[-        ] process > luciphor                     -
Pulling Singularity image docker://nfcore/proteomicslfq:1.0.0 [cache /nfs/users/mirimia/narecco/projects/07_Suz12AS/proteomicslfq/singularity/nfcore-proteomicslfq-1.0.0.img]
No such variable: ch_expdesign

 -- Check script 'main.nf' at line: 1054 or see '.nextflow.log' file for more details
````

Now, according to the documentation I am not required to specify an experimental design file with `--expdesign` as my samples are all unrelated, unfractionated runs. Or should I?

When I look at the `.nexflow.config` this is the cryptic output I get.

```
Nov-03 13:47:58.298 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: Unknown variable 'ch_expdesign'
	at sun.reflect.GeneratedConstructorAccessor43.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:265)
	at nextflow.script.ProcessConfig.getProperty(ProcessConfig.groovy:273)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:313)
	at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:303)
	at groovy.lang.Closure.getProperty(Closure.java:288)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at Script_d50c0614$_runScript_closure36.doCall(Script_d50c0614:1054)
	at Script_d50c0614$_runScript_closure36.doCall(Script_d50c0614)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at nextflow.script.ProcessFactory.createProcessor(ProcessFactory.groovy:95)
	at nextflow.script.ProcessFactory$createProcessor.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at nextflow.script.ProcessFactory$createProcessor.call(Unknown Source)
	at nextflow.script.BaseScript.process(BaseScript.groovy:115)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at Script_d50c0614.runScript(Script_d50c0614:1043)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:219)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:219)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:127)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:274)
	at nextflow.cli.Launcher.run(Launcher.groovy:466)
	at nextflow.cli.Launcher.main(Launcher.groovy:648)
```

Thanks a lot! 
Nicco

**Comment by jpfeuffer** [comment]
Hi Nicco,

I think you are right and this is an error in the docs. While the used tool does not require the experimental design, I think we forgot to include that logic in the workflow parameters.
Anyhow, since you have different conditions, it may make sense to construct a simple experimental design anyway. Not sure if I would call the samples from a common condition unrelated. Aren't they rather biological or technical replicates?

**Comment by Ni-Ar** [comment]
Ah okay, so I must included a design table. Yes my samples belong to 2 conditions and in total I have 3 biological replicates per condition. How would I construct a experimental design that is compatible with OpenMS format?

**Comment by jpfeuffer** [comment]
A small description can be found [here](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/classOpenMS_1_1ExperimentalDesign.html#details).

But for you, I think it should be just:

| Fraction_Group | Fraction | Spectra_Filepath | Label | MSstats_Condition | MSstats_BioReplicate |
|:--------------:|:--------:|:----------------:|:-----:|:-----------------:|:--------------------:|
| 1              | 1        | c1.mzML          | 1     | c                 | 1                    |
| 2              | 1        | c2.mzML          | 1     | c                 | 2                    |
| 3              | 1        | c3.mzML          | 1     | c                 | 3                    |
| 4              | 1        | t1.mzML          | 1     | t                 | 4                    |
| 5              | 1        | t2.mzML          | 1     | t                 | 5                    |
| 6              | 1        | t3.mzML          | 1     | t                 | 6                    |
|                |          |                  |       |                   |                      |

**Comment by Ni-Ar** [comment]
Cool thanks a lot!
