### ISSUE TITLE
Luciphor not working 

### ISSUE THREAD

**Issue by ypriverol** [nf-core/proteomicslfq#67]
May-12 01:17:05.539 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'luciphor (1)'

Caused by:
  Process `luciphor (1)` terminated with an error exit status (1)

Command executed:

  LuciphorAdapter    -id 020320_FeNTA_phospho_idx_feat_perc_filter_switched.idXML \
                     -in 020320_FeNTA_phospho.mzML \
                     -out 020320_FeNTA_phospho_idx_feat_perc_filter_switched_luciphor.idXML \
                     -threads 2 \
                     -num_threads 2 \
                     -target_modifications 'Phospho (S)' 'Phospho (T)' 'Phospho (Y)' \
                     -fragment_method HCD \
                      \
                      \
                      \
                     -max_charge_state 4 \
                     -max_peptide_length 40 \
                     > 020320_FeNTA_phospho_idx_feat_perc_filter_switched_scoreswitcher.log

Command exit status:
  1

Command output:
  (empty)

Command wrapper:
  
      pstat() {
          local x_pid=$1
          local STATUS=$(2> /dev/null < /proc/$1/status egrep 'Vm|ctxt')
  
          if [ $? = 0 ]; then
          local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
          local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
          local x_peak=$(echo "$STATUS" | egrep 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
          local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
          local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
          local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
          cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
          fi
      }
  
      pwalk() {
          pstat $1
          for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
      }
  
      pwalk $1
  }
  
  nxf_stat() {
      cpu_stat=()
      nxf_tree $1
  
      declare -a sum=(0 0 0 0 0 0 0 0)
  
  (... more ...)
  ------------------------------------------------------------
  
  Exited with exit code 1.
  
  Resource usage summary:
  
      CPU time :                                   349.28 sec.
      Max Memory :                                 6949 MB
      Average Memory :                             2848.86 MB
      Total Requested Memory :                     8192.00 MB
      Delta Memory :                               1243.00 MB
      Max Swap :                                   8364 MB
      Max Processes :                              10
      Max Threads :                                13
      Run time :                                   211 sec.
      Turnaround time :                            198 sec.
  
  The output (if any) is above this job summary.

Work dir:
  /nfs/production3/pride/prod/cluster/reanalysis/PXD018241-phospho/work/1b/3e5863cfaac78d205ac0dec563350e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by ypriverol** [comment]
Looks like luciphor is not in the path. @julianus do you know how to use luciphor in conda mode 

```
pho_idx_feat_perc_filter_switched_scoreswitcher.log 
File '/homes/pst_prd/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/homes/pst_prd/.OpenMS/OpenMS.ini' with defaults!
Unknown (or deprecated) Parameter 'xtandem_executable' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'omssa_executable' given in outdated parameter file! Ignoring parameter. 
Default-Parameter 'temp_dir' overridden: '' --> '/nfs/pride/work/archive/oms-platform/temp/'!
Unknown (or deprecated) Parameter 'swissprot' given in outdated parameter file! Ignoring parameter. 
Default-Parameter 'threads' overridden: '1' --> '2'!
File '/homes/pst_prd/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/homes/pst_prd/.OpenMS/OpenMS.ini' with defaults!
Unknown (or deprecated) Parameter 'xtandem_executable' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'omssa_executable' given in outdated parameter file! Ignoring parameter. 
Default-Parameter 'temp_dir' overridden: '' --> '/nfs/pride/work/archive/oms-platform/temp/'!
Unknown (or deprecated) Parameter 'swissprot' given in outdated parameter file! Ignoring parameter. 
Default-Parameter 'threads' overridden: '1' --> '2'!
Progress of 'loading spectra list':
  41.47 %               
  74.38 %               
-- done [took 02:56 m (CPU), 01:30 m (Wall)] -- 
Progress of 'loading chromatogram list':
-- done [took 0.03 s (CPU), 0.03 s (Wall)] -- 
Input file 'luciphor2.jar' could not be found (by searching on PATH). Either provide a full filepath or fix your PATH environment!
Error: File not found (the file 'luciphor2.jar' could not be found)
```

**Comment by ypriverol** [comment]
This first error is related with the fact that conda jars and openMS are not working well together. This needs to be fixed if we want to use conda in LSF or HPC environments.

**Comment by ypriverol** [comment]
I fixed manually the Luciphor but another error just appears, looks like mzML parser error: 

```
Mods to score:
Y	79.966331
T	79.966331
S	79.966331

Allowed Neutral Losses:
sty-H3PO4	-97.9769
<X>-H3PO4	-97.9769  (Decoy NL)

Reading PSMs from pepXML file: /nfs/pride/work/archive/oms-platform/temp/20200512_105329_hx-noah-11-03.ebi.ac.uk_172659_1/020320_TiO2_Phospho_idx_feat_perc_filter_switched.pepXML
10881 Candidate PSMs read in.

Reading spectra from /nfs/production3/pride/prod/cluster/reanalysis/PXD018241-phospho/work/2a/266e2e6b0ef22c01d473ca36cec5d6  (MZML format)
This can take a while so please be patient.

020320_TiO2_Phospho.mzML:  Exception in thread "main" umich.ms.fileio.exceptions.RunHeaderParsingException: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"mzML"). Expected elements are <{h
ttp://psi.hupo.org/ms/mzml}mzML>
	at umich.ms.fileio.filetypes.mzxml.XmlBasedRunHeaderParser.parseHeaderWithJAXB(XmlBasedRunHeaderParser.java:72)
	at umich.ms.fileio.filetypes.mzml.MZMLRunHeaderParser.parse(MZMLRunHeaderParser.java:72)
	at umich.ms.fileio.filetypes.mzml.MZMLFile.parseRunInfo(MZMLFile.java:92)
	at umich.ms.fileio.filetypes.AbstractLCMSDataSource.fetchRunInfo(AbstractLCMSDataSource.java:74)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parseScan(AbstractXMLBasedDataSource.java:640)
	at lucxor.globals.read_mzML(globals.java:676)
	at lucxor.globals.read_in_spectra(globals.java:646)
	at lucxor.LucXor.main(LucXor.java:71)
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"mzML"). Expected elements are <{http://psi.hupo.org/ms/mzml}mzML>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at umich.ms.fileio.filetypes.mzxml.XmlBasedRunHeaderParser.parseHeaderWithJAXB(XmlBasedRunHeaderParser.java:69)
	... 7 more

Exit code: 1
LuciphorAdapter took 02:16 m (wall), 03:53 m (CPU), 7.35 s (system), 03:45 m (user).
```

**Comment by ypriverol** [comment]
This is the head lines of the mzML file: 

```
<indexedmzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd" xmlns="http://psi.hupo.org/ms/mzml">
  <mzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd" version="1.1.0" id="020320_FeNTA_phospho">
    <cvList count="2">
      <cv id="MS" fullName="Mass spectrometry ontology" version="4.1.12" URI="https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo" />
      <cv id="UO" fullName="Unit Ontology" version="09:04:2014" URI="https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/master/unit.obo" />
    </cvList>
    <fileDescription>
      <fileContent>
        <cvParam cvRef="MS" accession="MS:1000579" value="" name="MS1 spectrum" />
        <cvParam cvRef="MS" accession="MS:1000580" value="" name="MSn spectrum" />
      </fileContent>
```

**Comment by ypriverol** [comment]
After replacing the lastest version of LUciphor now we have the following error in the adapter: 

```
Z = 3:  b-ions Intensity: (mean, std): (0.4351, 1.1875) N = 117453
Z = 3:  y-ions Intensity: (mean, std): (0.7116, 1.364) N = 116653
Z = 3:  Matched Peak Distance: (mean, std): (0.0067, 0.1122) N = 234106
Z = 3:  Noise peak Intensity: (mean, std): (-0.1737, 1.1088) N = 234106

+3  Estimating NP Model for b-ion intensities
+3  Estimating NP Model for y-ion intensities
+3  Estimating NP Model for noise peak intensities
+3  Estimating NP Model for b and y ions m/z distances

Z = 4:  b-ions Intensity: (mean, std): (0.4087, 1.2446) N = 20521
Z = 4:  y-ions Intensity: (mean, std): (0.5738, 1.3493) N = 20128
Z = 4:  Matched Peak Distance: (mean, std): (0.0369, 0.126) N = 40649
Z = 4:  Noise peak Intensity: (mean, std): (-0.1981, 1.1836) N = 90649

+4  Estimating NP Model for b-ion intensities
+4  Estimating NP Model for y-ion intensities
+4  Estimating NP Model for noise peak intensities
+4  Estimating NP Model for b and y ions m/z distances


[ 0 ] Estimating FLR with decoys (2 threads)...
100 200 300 400 500 600 700 800 900 1000 
1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 
2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 
3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 
4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 
5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 
6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 
7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 
8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 
9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 
10100 10200 10300 10400 10500 10600 10700 10800 

Computing False Localization Rate (FLR)
FLR bandwidth (pos): 4.583122
FLR bandwidth (neg): 0.172596

[ 1 ] Scoring 10881 PSMs (2 threads)...
100 200 300 400 500 600 700 800 900 1000 
1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 
2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 
3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 
4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 
5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 
6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 
7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 
8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 
9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 
10100 10200 10300 10400 10500 10600 10700 10800 

Results written to '/nfs/production3/pride/prod/cluster/reanalysis/PXD018241-p
hospho/work/f6/00b7b8503dce7f1f91f5ebfd1f266f/020320_TiO2_Phospho_idx_feat_per
c_filter_switched_luciphor.idXML'

Total run time (HH:MM:SS) = 00:30:57


Exit code: 0
DEBUG: Printing standard output and error of /nfs/production3/pride/prod/clust
er/reanalysis/PXD018241-phospho/work/conda/nf-core-proteomicslfq-1.0dev-29c755
6a955f837808dd304c737c92f7/bin/java


Executed /nfs/production3/pride/prod/cluster/reanalysis/PXD018241-phospho/work
/conda/nf-core-proteomicslfq-1.0dev-29c7556a955f837808dd304c737c92f7/bin/java 
successfully!
Error: Unexpected internal error (the element 'spectrum with RT 467.6000000000
00023' could not be found)
Error occurred in line 83 of file /opt/conda/conda-bld/openms-meta_15887097047
46/work/src/openms/source/METADATA/SpectrumLookup.cpp (in function: OpenMS::Si
ze OpenMS::SpectrumLookup::findByRT(double) const) !
Keeping temporary files in directory '/nfs/pride/work/archive/oms-platform/tem
p//20200514_211929_hx-noah-05-01.ebi.ac.uk_18746_1/'. Set debug level to 2 or 
lower to remove them.
```

**Comment by ypriverol** [comment]
@julianus @timosachsenberg the output of the Luxifor is the following: 

```
specId	peptide	predictedPep1	predictedPep2	numPPS	numRPS	pepProphet	deltaScore	pep1score	pep2score	globalFLR	localFLR
020320_TiO2_Phospho.609.609.2	KSPGSTSR	KsPGSTSR	KSPGsTSR	4	1	0.541402	3.6524229999999998	9.757372	6.1049
49	0.012182503181049398	0.05962601001403518
020320_TiO2_Phospho.1199.1199.2	KSGLSSR	KsGLSSR	KSGLsSR	3	1	0.737636	5.522532	8.812307	3.289775	0.00256500566458221260.013322573905258435
020320_TiO2_Phospho.1590.1590.2	KSSSKGPQR	KSsSKGPQR	KsSSKGPQR	3	1	0.785979	2.894038000000002	21.386147	18.492
109	0.02091082723569643	0.1936439086261059
020320_TiO2_Phospho.1591.1591.2	QSALGSR	QSALGsR	QsALGSR	2	1	0.709713	0.24712800000000001	11.881225	11.634097	0.487696015268
80557	1.0
020320_TiO2_Phospho.1683.1683.2	KAPKSPAK	KAPKsPAK	KAPKsPAK	1	1	0.99849112	50.797067	50.797067	0.0	1.8707
275426397562E-8	1.3706567625620777E-9
```
